### ISSUE TITLE
Notes on testing on a Pi Zero W with Raspian Stretch Lite

### ISSUE THREAD

**Issue by emceeaich** [claudiobizzotto/ipfs-rpi#11]
Trying to run from the command line on a Pi Zero W using the `ipfs daemon` command (after disabling the auto-launched daemon) I get as far as seeing peers appear and then:
 
```
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```
I don't know if the Pi Zero W is just underpowered. I'll try with a regular Pi, but I think if I don't hear of any other successes, I'm tempted to update README.md with the note it doesn't work on a Pi Zero. 

I'll set up a regular Pi 3 tomorrow to confirm it's not something I'm doing incorrectly.

**Comment by claudiobizzotto** [comment]
Hi @emceeaich, any success with the RPi 3? Also, what's the OS running on your Pi Zero?

**Comment by emceeaich** [comment]
I'm using the June 2018 Raspbian Stretch Lite on a RPi 3 B, and able to get it up and running. I followed the instructions at https://ipfs.io/docs/examples/example-viewer/example#../websites/README.md and was able to publish a site at one of my domain names!
