### ISSUE TITLE
Start with pre-fedault folders

### ISSUE THREAD

**Issue by whiteyhat** [claudiobizzotto/ipfs-rpi#13]
Hi @claudiobizzotto ,

I am wondering If it is possible to automate a script that as soon as the IPFS is running on the pi it adds a folder (obtained through a `sudo git clone` or locally) to be deployed in the IPFS network.

In case of this being possible, could you please give me some indications to do it in this repo?

**Comment by claudiobizzotto** [comment]
Hi @whiteyhat. Are you looking for some sort of automation (maybe for CI/CD purposes)? If so, you can fork this repo and add that functionality to the scripts. In that case, `install` would take care of

1) downloading/cloning the repository you're interested in
2) pinning the content to IPFS

and `uninstall` would

1) unpin the content from IPFS
2) delete the folder from the local filesystem

Let me know if that makes sense.

**Comment by claudiobizzotto** [comment]
Closing this as resolved.
