### ISSUE TITLE
Change the default IPFS data path

### ISSUE THREAD

**Issue by andrasfuchs** [claudiobizzotto/ipfs-rpi#14]
What exactly do I need to change on the Raspberry Pi to have a different IPFS path?
I would like to use an external drive as my IPFS block storage.

**Comment by claudiobizzotto** [comment]
Changing lines 53 and 57 inside the [installer](https://github.com/claudiobizzotto/ipfs-rpi/blob/master/install) should do it. Something like this (assuming your external hard drive is mounted at `/mnt/ipfs/`):

```shell
# L53
[ ! -d /mnt/ipfs/.ipfs ] && ipfs init

# L57
ipfs_path=/mnt/ipfs/.ipfs
```

Make sure you make similar changes in the uninstall script if you plan on using it as well.

**Comment by andrasfuchs** [comment]
Thank you for your reply, @claudiobizzotto!

I created a symlink in the end, and it works just fine.
