### ISSUE TITLE
IPFS daemon starts multiple times

### ISSUE THREAD

**Issue by micheldejoode** [claudiobizzotto/ipfs-rpi#8]
Hi, 

First of all: thanks for creating this installer. 

I have one isue with it:

After installing IPFS on my Raspberry Pi, the IPFS daemon seams to start multiple times. If I look at htop, it shows 10 or 20 IPFS daemons. It gets more after some time too. Any idea why this is? I can see it eats all the memory.

**Comment by claudiobizzotto** [comment]
Hi Michel,

whoa, this is unacceptable! 😁 

Can you try the following?

- temporarily disable the service with `sudo systemctl disable ipfs-daemon`
- kill all existing processes with `killall ipfs-daemon`
- start a daemon, but this time bypassing the service: `ipfs daemon`

Wait a few minutes and check how many daemons are running.

**Comment by claudiobizzotto** [comment]
Hi Michel,

can you paste the output of the following command here?

```SHELL
cat /lib/systemd/system/ipfs-daemon.service /etc/init/ipfs-daemon.conf
```

**Comment by micheldejoode** [comment]
Hi,

Thanks for your help!

The command gives this output:
[Unit]
Description=IPFS daemon
Wants=network.target
After=network.target

[Service]
Type=simple
Environment=IPFS_PATH=/home/pi/.ipfs
ExecStart=/usr/local/bin/ipfs daemon
ExecStop=/usr/bin/pkill -f ipfs
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target

cat: /etc/init/ipfs-daemon.conf: No such file or directory

**Comment by micheldejoode** [comment]
Hi,
On the first command i get: 0 loaded units listed, so that's good i think. 

On "ipfs daemon" (as "pi" user) i get the following error:
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Error: cannot acquire lock: Lock Create of /home/pi/.ipfs/repo.lock failed: open /home/pi/.ipfs/repo.lock: permission denied

It looks like it needs a sudo. But, if i do a sudo ipfs daemon, than it works, but loads all the different daemons again.  

I'm using a raspberry pi 2, with raspbian stretch lite.

**Comment by claudiobizzotto** [comment]
What happens if you remove the lock file and then start the daemon?

```SHELL
$ # Still as user "pi"
$ sudo rm /home/pi/.ipfs/repo.lock
$ ipfs daemon
```

**Comment by micheldejoode** [comment]
hi,

After removing the lock file , it says (after command ipfs daemon):

Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.2.14/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/QmUVjEeeH3ENneLDNdmJno4VbNBtnoS9hfda2a6Qu7ePxj
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.2.14/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Error: serveHTTPApi: SetAPIAddr() failed: open /home/pi/.ipfs/api: permission denied

With sudo ipfs daemon it works, but load the different ipfs daemons again...

**Comment by micheldejoode** [comment]
![htop](https://user-images.githubusercontent.com/5420967/39233116-be43495e-486f-11e8-923f-1217c4ac0a6b.jpg)

Here is a screenshot of htop.

**Comment by micheldejoode** [comment]
Somehow i managed to run ipfs daemon without sudo, and running as pi, but it still loads multiple daemons...

**Comment by claudiobizzotto** [comment]
Hi Michel,

you shouldn't need Raspbian Desktop to make this work - I'm running headless Raspbian on two of my RPis and they perform all right.

I suspect you've run the installer while logged in as `root`. Can you check if there's a `/root/.ipfs` folder in your RPi?

If there is such a folder, you'll need to uninstall IPFS and rerun the installer as a regular administrator user (like the default `pi`). Let me know and I can show you how to do that.

**Comment by micheldejoode** [comment]
I've re-installed Raspbian lite to make sure it's not corrupted or something. I've run the install as "pi" user, but when i look at htop, it says that the ipfs daemon is run as root. 

When i stop and disable the daemon, and start it manually as "pi", it is indeed loaded as "pi", but still runs multiple daemons.

**Comment by claudiobizzotto** [comment]
Michel, I think everything is working as expected.

Firstly, the service should be running as `root`.

As for the multiple daemons, after looking closer at the image you've posted, those are just the threads created by IPFS - they are not separate processes/daemons. It's confusing, but that's how `htop` displays things (check [this thread](https://unix.stackexchange.com/a/10403) for more information).

**Comment by micheldejoode** [comment]
Hi Claudio, i was already afraid this was the case, i was searching for the meaning of the colors of htop already. Thank you so much for helping me out! I'll leave it this way.
